const { Trip, sequelize } = require('../src/models');

const popularTrips = [
  // 1. HÀ NỘI
  {
    id: 'job_hn_01',
    badge: 'Cuốc HOT',
    pickup_location: 'Quán Bia Hải Xồm, 86 Lê Trọng Tấn, Thanh Xuân, Hà Nội',
    dropoff_location: 'Chung cư Imperia Garden, 203 Nguyễn Huy Tưởng, Hà Nội',
    distance_km: 5.2,
    estimated_minutes: 15,
    price: 130000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: 'Vừa xong',
    customer_name: 'Anh Tuấn',
    customer_phone: '0983 234 567'
  },
  {
    id: 'job_hn_02',
    badge: 'VIP',
    pickup_location: 'Nhà hàng Lã Vọng, Hoàng Cầu, Đống Đa, Hà Nội',
    dropoff_location: 'Khu đô thị Ciputra, Tây Hồ, Hà Nội',
    distance_km: 11.5,
    estimated_minutes: 25,
    price: 220000,
    service_tags: ['Lái xe hộ', 'VIP'],
    status: 'new',
    is_virtual: true,
    time_posted: '2 phút trước',
    customer_name: 'Anh Long',
    customer_phone: '0912 888 999'
  },
  {
    id: 'job_hn_03',
    badge: 'Mới',
    pickup_location: '19/5 Trúc Bạch, Ba Đình, Hà Nội',
    dropoff_location: 'Vinhomes Ocean Park 1, Gia Lâm, Hà Nội',
    distance_km: 18.2,
    estimated_minutes: 32,
    price: 280000,
    service_tags: ['Lái xe hộ', 'Đường dài'],
    status: 'new',
    is_virtual: true,
    time_posted: '3 phút trước',
    customer_name: 'Chị Hương',
    customer_phone: '0977 123 789'
  },
  {
    id: 'job_hn_04',
    badge: 'Cuốc HOT',
    pickup_location: 'Trung tâm Hội nghị Quốc gia, Mễ Trì, Nam Từ Liêm, Hà Nội',
    dropoff_location: 'Sân bay Quốc tế Nội Bài (Nhà ga T1), Hà Nội',
    distance_km: 28.5,
    estimated_minutes: 35,
    price: 350000,
    service_tags: ['Lái xe hộ', 'Đưa đón sân bay'],
    status: 'new',
    is_virtual: true,
    time_posted: '5 phút trước',
    customer_name: 'Anh Dũng',
    customer_phone: '0904 555 666'
  },
  {
    id: 'job_hn_05',
    badge: 'Mới',
    pickup_location: 'Quán Nhậu Tự Do, 67 Khúc Thừa Dụ, Cầu Giấy, Hà Nội',
    dropoff_location: 'Khu đô thị Ecopark, Văn Giang, Hưng Yên',
    distance_km: 24.0,
    estimated_minutes: 40,
    price: 360000,
    service_tags: ['Lái xe hộ', 'Đường dài'],
    status: 'new',
    is_virtual: true,
    time_posted: '7 phút trước',
    customer_name: 'Anh Nam',
    customer_phone: '0966 333 444'
  },
  {
    id: 'job_hn_06',
    badge: 'Mới',
    pickup_location: 'Phố đi bộ Hồ Gươm, 1 Đinh Tiên Hoàng, Hoàn Kiếm, Hà Nội',
    dropoff_location: 'Vinhomes Smart City, Tây Mỗ, Nam Từ Liêm, Hà Nội',
    distance_km: 16.0,
    estimated_minutes: 30,
    price: 250000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '10 phút trước',
    customer_name: 'Anh Quang',
    customer_phone: '0988 777 666'
  },
  {
    id: 'job_hn_07',
    badge: 'VIP',
    pickup_location: 'Sân Golf Long Biên, Phúc Đồng, Long Biên, Hà Nội',
    dropoff_location: 'KĐT Splendora Bắc An Khánh, Hoài Đức, Hà Nội',
    distance_km: 27.0,
    estimated_minutes: 38,
    price: 400000,
    service_tags: ['Lái xe hộ', 'VIP'],
    status: 'new',
    is_virtual: true,
    time_posted: '12 phút trước',
    customer_name: 'Anh Thắng',
    customer_phone: '0915 222 333'
  },
  {
    id: 'job_hn_08',
    badge: 'Mới',
    pickup_location: 'Nhà hàng Sen Tây Hồ, Lạc Long Quân, Tây Hồ, Hà Nội',
    dropoff_location: 'Times City, 458 Minh Khai, Hai Bà Trưng, Hà Nội',
    distance_km: 14.5,
    estimated_minutes: 28,
    price: 220000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '15 phút trước',
    customer_name: 'Chị Mai',
    customer_phone: '0936 111 222'
  },
  {
    id: 'job_hn_09',
    badge: 'Mới',
    pickup_location: 'Bến xe Mỹ Đình, Phạm Hùng, Cầu Giấy, Hà Nội',
    dropoff_location: 'TP. Bắc Ninh (Ngã 6 TP. Bắc Ninh)',
    distance_km: 38.0,
    estimated_minutes: 45,
    price: 480000,
    service_tags: ['Lái xe hộ', 'Đường dài'],
    status: 'new',
    is_virtual: true,
    time_posted: '18 phút trước',
    customer_name: 'Anh Bình',
    customer_phone: '0979 444 555'
  },
  {
    id: 'job_hn_10',
    badge: 'Cuốc HOT',
    pickup_location: 'Keangnam Landmark 72, Mễ Trì, Hà Nội',
    dropoff_location: 'Quảng trường Hồ Chí Minh, TP. Vĩnh Yên, Vĩnh Phúc',
    distance_km: 52.0,
    estimated_minutes: 55,
    price: 650000,
    service_tags: ['Đường dài', 'Xe tiện chuyến'],
    status: 'new',
    is_virtual: true,
    time_posted: '20 phút trước',
    customer_name: 'Anh Kiên',
    customer_phone: '0982 999 888'
  },

  // 2. TP. HỒ CHÍ MINH
  {
    id: 'job_hcm_01',
    badge: 'Cuốc HOT',
    pickup_location: 'Nhà hàng Dìn Ký, 137C Nguyễn Trãi, Quận 1, TP. HCM',
    dropoff_location: 'Chung cư Masteri Thảo Điền, TP. Thủ Đức, TP. HCM',
    distance_km: 9.8,
    estimated_minutes: 22,
    price: 170000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '1 phút trước',
    customer_name: 'Anh Khoa',
    customer_phone: '0903 123 456'
  },
  {
    id: 'job_hcm_02',
    badge: 'Mới',
    pickup_location: 'Bia Sệt 142, Bờ Kè Hoàng Sa, Quận 3, TP. HCM',
    dropoff_location: 'Vinhomes Central Park, 208 Nguyễn Hữu Cảnh, Bình Thạnh',
    distance_km: 6.2,
    estimated_minutes: 16,
    price: 140000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '4 phút trước',
    customer_name: 'Anh Minh',
    customer_phone: '0918 345 678'
  },
  {
    id: 'job_hcm_03',
    badge: 'Mới',
    pickup_location: 'Nhà hàng Hàng Dương Quán, 132 đường 65, Quận 7, TP. HCM',
    dropoff_location: 'Khu đô thị Sala, Mai Chí Thọ, TP. Thủ Đức',
    distance_km: 8.5,
    estimated_minutes: 18,
    price: 160000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '6 phút trước',
    customer_name: 'Chị Lan',
    customer_phone: '0908 678 901'
  },
  {
    id: 'job_hcm_04',
    badge: 'Cuốc HOT',
    pickup_location: 'Sân bay Tân Sơn Nhất (Cột 12 Ga Quốc Nội), TP. HCM',
    dropoff_location: 'Khu đô thị Phú Mỹ Hưng (Nguyễn Lương Bằng), Quận 7',
    distance_km: 15.0,
    estimated_minutes: 35,
    price: 290000,
    service_tags: ['Lái xe hộ', 'Đưa đón sân bay'],
    status: 'new',
    is_virtual: true,
    time_posted: '8 phút trước',
    customer_name: 'Anh Trí',
    customer_phone: '0938 111 999'
  },
  {
    id: 'job_hcm_05',
    badge: 'Mới',
    pickup_location: 'Phố Tây Bùi Viện, Phường Phạm Ngũ Lão, Quận 1, TP. HCM',
    dropoff_location: 'Chung cư Celadon City, Bờ Bao Tân Thắng, Tân Phú',
    distance_km: 12.5,
    estimated_minutes: 28,
    price: 200000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '11 phút trước',
    customer_name: 'Anh Đức',
    customer_phone: '0902 444 333'
  },
  {
    id: 'job_hcm_06',
    badge: 'Mới',
    pickup_location: 'Quán ốc Oanh, 534 Vĩnh Khánh, Phường 8, Quận 4, TP. HCM',
    dropoff_location: 'KĐT Mizuki Park, Nguyễn Văn Linh, Bình Chánh',
    distance_km: 10.8,
    estimated_minutes: 24,
    price: 180000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '14 phút trước',
    customer_name: 'Anh Thịnh',
    customer_phone: '0978 222 111'
  },
  {
    id: 'job_hcm_07',
    badge: 'VIP',
    pickup_location: 'Toà nhà Landmark 81, 720A Điện Biên Phủ, Bình Thạnh',
    dropoff_location: 'Trung tâm Hành chính TP. Dĩ An, Tỉnh Bình Dương',
    distance_km: 21.0,
    estimated_minutes: 35,
    price: 320000,
    service_tags: ['Lái xe hộ', 'Đường dài'],
    status: 'new',
    is_virtual: true,
    time_posted: '16 phút trước',
    customer_name: 'Anh Huy',
    customer_phone: '0909 888 777'
  },
  {
    id: 'job_hcm_08',
    badge: 'Mới',
    pickup_location: 'Nhà hàng Vườn Phố, Sân vận động Quân khu 7, Phú Nhuận',
    dropoff_location: 'Đường 5 nối dài, TP. Biên Hòa, Tỉnh Đồng Nai',
    distance_km: 32.5,
    estimated_minutes: 45,
    price: 460000,
    service_tags: ['Lái xe hộ', 'Đường dài'],
    status: 'new',
    is_virtual: true,
    time_posted: '19 phút trước',
    customer_name: 'Anh Tấn',
    customer_phone: '0913 555 444'
  },
  {
    id: 'job_hcm_09',
    badge: 'Mới',
    pickup_location: 'Trung tâm Thương mại Takashimaya, Nam Kỳ Khởi Nghĩa, Q1',
    dropoff_location: 'Khu công nghiệp VSIP 1, Thuận An, Bình Dương',
    distance_km: 26.0,
    estimated_minutes: 40,
    price: 390000,
    service_tags: ['Lái xe hộ', 'Đường dài'],
    status: 'new',
    is_virtual: true,
    time_posted: '22 phút trước',
    customer_name: 'Anh Phong',
    customer_phone: '0937 666 555'
  },
  {
    id: 'job_hcm_10',
    badge: 'Mới',
    pickup_location: 'Làng ẩm thực Tây Nam Bộ, Đường Tên Lửa, Bình Tân',
    dropoff_location: 'Thị trấn Bến Lức, Tỉnh Long An',
    distance_km: 25.0,
    estimated_minutes: 36,
    price: 370000,
    service_tags: ['Lái xe hộ', 'Đường dài'],
    status: 'new',
    is_virtual: true,
    time_posted: '25 phút trước',
    customer_name: 'Anh Vũ',
    customer_phone: '0945 777 888'
  },

  // 3. ĐÀ NẴNG & HỘI AN
  {
    id: 'job_dn_01',
    badge: 'Cuốc HOT',
    pickup_location: 'Quán Cơm Niêu Nhà Đỏ, 86 Nguyễn Tri Phương, Đà Nẵng',
    dropoff_location: 'Bãi biển Mỹ Khê (Đường Võ Nguyên Giáp), Ngũ Hành Sơn',
    distance_km: 6.8,
    estimated_minutes: 15,
    price: 120000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '3 phút trước',
    customer_name: 'Anh Nghĩa',
    customer_phone: '0905 123 456'
  },
  {
    id: 'job_dn_02',
    badge: 'Mới',
    pickup_location: 'Nhà hàng Hải Sản Bé Mặn, Lô 11 Võ Nguyên Giáp, Sơn Trà',
    dropoff_location: 'Khu đô thị sinh thái Hòa Xuân, Cẩm Lệ, Đà Nẵng',
    distance_km: 11.2,
    estimated_minutes: 20,
    price: 170000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '6 phút trước',
    customer_name: 'Anh Châu',
    customer_phone: '0935 234 567'
  },
  {
    id: 'job_dn_03',
    badge: 'Mới',
    pickup_location: 'Sân bay Quốc tế Đà Nẵng (Nhà ga T1)',
    dropoff_location: 'Phố cổ Hội An (Trần Phú), TP. Hội An, Quảng Nam',
    distance_km: 29.5,
    estimated_minutes: 40,
    price: 350000,
    service_tags: ['Lái xe hộ', 'Đưa đón sân bay'],
    status: 'new',
    is_virtual: true,
    time_posted: '9 phút trước',
    customer_name: 'Chị Yến',
    customer_phone: '0984 345 678'
  },
  {
    id: 'job_dn_04',
    badge: 'VIP',
    pickup_location: 'Bar Sky36, Khách sạn Novotel Bạch Đằng, Đà Nẵng',
    dropoff_location: 'InterContinental Danang Sun Peninsula Resort, Bán đảo Sơn Trà',
    distance_km: 17.5,
    estimated_minutes: 28,
    price: 290000,
    service_tags: ['Lái xe hộ', 'VIP'],
    status: 'new',
    is_virtual: true,
    time_posted: '13 phút trước',
    customer_name: 'Anh Duy',
    customer_phone: '0914 456 789'
  },
  {
    id: 'job_dn_05',
    badge: 'Mới',
    pickup_location: 'Cầu Rồng, Đường Trần Hưng Đạo, Sơn Trà, Đà Nẵng',
    dropoff_location: 'Khu du lịch Bà Nà Hills, Hòa Ninh, Hòa Vang',
    distance_km: 28.0,
    estimated_minutes: 38,
    price: 380000,
    service_tags: ['Đường dài', 'Xe tiện chuyến'],
    status: 'new',
    is_virtual: true,
    time_posted: '17 phút trước',
    customer_name: 'Anh Tài',
    customer_phone: '0973 567 890'
  },

  // 4. THANH HOÁ
  {
    id: 'job_th_01',
    badge: 'Mới',
    pickup_location: 'Nhà hàng Dạ Lan, 01 Phan Chu Trinh, TP. Thanh Hoá',
    dropoff_location: 'Quảng trường Lam Sơn, Đường Hạc Thành, TP. Thanh Hoá',
    distance_km: 3.2,
    estimated_minutes: 9,
    price: 90000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '2 phút trước',
    customer_name: 'Anh Tuấn Anh',
    customer_phone: '0912 345 111'
  },
  {
    id: 'job_th_02',
    badge: 'Cuốc HOT',
    pickup_location: 'Bia hơi Hà Nội, 150 Dương Đình Nghệ, TP. Thanh Hoá',
    dropoff_location: 'FLC Sầm Sơn Beach & Golf Resort, Đường Hồ Xuân Hương, Sầm Sơn',
    distance_km: 18.5,
    estimated_minutes: 28,
    price: 230000,
    service_tags: ['Lái xe hộ', 'Đường dài'],
    status: 'new',
    is_virtual: true,
    time_posted: '5 phút trước',
    customer_name: 'Anh Sơn',
    customer_phone: '0988 222 333'
  },
  {
    id: 'job_th_03',
    badge: 'Mới',
    pickup_location: 'Vincom Plaza Thanh Hoá, 27 Trần Phú, Điện Biên, TP. Thanh Hoá',
    dropoff_location: 'Bãi biển Hải Tiến, Hoằng Hóa, Thanh Hóa',
    distance_km: 22.0,
    estimated_minutes: 32,
    price: 270000,
    service_tags: ['Lái xe hộ', 'Đường dài'],
    status: 'new',
    is_virtual: true,
    time_posted: '8 phút trước',
    customer_name: 'Chị Thảo',
    customer_phone: '0975 666 777'
  },
  {
    id: 'job_th_04',
    badge: 'Mới',
    pickup_location: 'Bệnh viện Đa khoa tỉnh Thanh Hoá, 181 Hải Thượng Lãn Ông',
    dropoff_location: 'Thị xã Bỉm Sơn (Khu công nghiệp Bỉm Sơn), Thanh Hoá',
    distance_km: 36.0,
    estimated_minutes: 45,
    price: 420000,
    service_tags: ['Đường dài', 'Xe tiện chuyến'],
    status: 'new',
    is_virtual: true,
    time_posted: '14 phút trước',
    customer_name: 'Anh Hậu',
    customer_phone: '0932 888 777'
  },
  {
    id: 'job_th_05',
    badge: 'VIP',
    pickup_location: 'Nhà khách 25B, Quang Trung, Ngọc Trạo, TP. Thanh Hoá',
    dropoff_location: 'Khu kinh tế Nghi Sơn, Thị xã Nghi Sơn, Thanh Hoá',
    distance_km: 58.0,
    estimated_minutes: 58,
    price: 680000,
    service_tags: ['Lái xe hộ', 'Đường dài', 'VIP'],
    status: 'new',
    is_virtual: true,
    time_posted: '21 phút trước',
    customer_name: 'Anh Khánh',
    customer_phone: '0904 999 111'
  },

  // 5. HẢI PHÒNG & QUẢNG NINH
  {
    id: 'job_hp_01',
    badge: 'Mới',
    pickup_location: 'Nhà hàng Gia Viên, 2B Bạch Đằng, Hạ Lý, Hồng Bàng, Hải Phòng',
    dropoff_location: 'Khu đô thị Vinhomes Imperia, Thượng Lý, Hải Phòng',
    distance_km: 3.8,
    estimated_minutes: 10,
    price: 100000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '4 phút trước',
    customer_name: 'Anh Phong',
    customer_phone: '0936 222 333'
  },
  {
    id: 'job_hp_02',
    badge: 'Cuốc HOT',
    pickup_location: 'Bia Vườn Nướng, Lê Hồng Phong, Đông Khê, Ngô Quyền, Hải Phòng',
    dropoff_location: 'Bãi biển Đồ Sơn (Khu 2), Đồ Sơn, Hải Phòng',
    distance_km: 22.0,
    estimated_minutes: 30,
    price: 280000,
    service_tags: ['Lái xe hộ', 'Đường dài'],
    status: 'new',
    is_virtual: true,
    time_posted: '7 phút trước',
    customer_name: 'Anh Hoàng',
    customer_phone: '0912 777 888'
  },
  {
    id: 'job_hp_03',
    badge: 'Mới',
    pickup_location: 'Sân bay Quốc tế Cát Bi, Lê Hồng Phong, Hải An, Hải Phòng',
    dropoff_location: 'Vinhomes Dragon Bay Hạ Long, Bến Đoan, Quảng Ninh',
    distance_km: 46.0,
    estimated_minutes: 48,
    price: 550000,
    service_tags: ['Lái xe hộ', 'Đưa đón sân bay'],
    status: 'new',
    is_virtual: true,
    time_posted: '11 phút trước',
    customer_name: 'Chị Nga',
    customer_phone: '0985 444 555'
  },
  {
    id: 'job_qn_01',
    badge: 'Mới',
    pickup_location: 'Cảng tàu khách Quốc tế Tuần Châu, TP. Hạ Long, Quảng Ninh',
    dropoff_location: 'Phố cổ Bãi Cháy, Đường Hạ Long, Bãi Cháy, Quảng Ninh',
    distance_km: 12.0,
    estimated_minutes: 18,
    price: 180000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '15 phút trước',
    customer_name: 'Anh Cường',
    customer_phone: '0978 111 444'
  },
  {
    id: 'job_qn_02',
    badge: 'Mới',
    pickup_location: 'Khách sạn Mường Thanh Luxury Hạ Long, Bãi Cháy',
    dropoff_location: 'Trung tâm TP. Cẩm Phả, Tỉnh Quảng Ninh',
    distance_km: 33.0,
    estimated_minutes: 42,
    price: 430000,
    service_tags: ['Đường dài', 'Xe tiện chuyến'],
    status: 'new',
    is_virtual: true,
    time_posted: '18 phút trước',
    customer_name: 'Anh Việt',
    customer_phone: '0906 333 888'
  },

  // 6. KHÁNH HOÀ (NHA TRANG) & LÂM ĐỒNG (ĐÀ LẠT)
  {
    id: 'job_nt_01',
    badge: 'Mới',
    pickup_location: 'Nhà hàng Champa Island, 304 Hai Tháng Tư, Nha Trang',
    dropoff_location: 'Vinpearl Condotel Beachfront, 78-80 Trần Phú, Lộc Thọ',
    distance_km: 5.8,
    estimated_minutes: 13,
    price: 110000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '5 phút trước',
    customer_name: 'Anh Bảo',
    customer_phone: '0905 555 444'
  },
  {
    id: 'job_nt_02',
    badge: 'Cuốc HOT',
    pickup_location: 'Sailing Club Nha Trang, 72-74 Trần Phú, Lộc Thọ, Nha Trang',
    dropoff_location: 'Resort Alma Bãi Dài, Huyện Cam Lâm, Khánh Hòa',
    distance_km: 26.5,
    estimated_minutes: 32,
    price: 330000,
    service_tags: ['Lái xe hộ', 'Đường dài'],
    status: 'new',
    is_virtual: true,
    time_posted: '9 phút trước',
    customer_name: 'Anh Tân',
    customer_phone: '0914 888 222'
  },
  {
    id: 'job_nt_03',
    badge: 'Mới',
    pickup_location: 'Sân bay Quốc tế Cam Ranh, Cam Nghĩa, Cam Ranh, Khánh Hòa',
    dropoff_location: 'Quảng trường 2 Tháng 4, Trần Phú, Nha Trang',
    distance_km: 36.0,
    estimated_minutes: 42,
    price: 390000,
    service_tags: ['Lái xe hộ', 'Đưa đón sân bay'],
    status: 'new',
    is_virtual: true,
    time_posted: '16 phút trước',
    customer_name: 'Chị Diệu',
    customer_phone: '0932 777 666'
  },
  {
    id: 'job_dl_01',
    badge: 'Mới',
    pickup_location: 'Nhà hàng Lẩu Bò Ba Toa, 1/29 Hoàng Diệu, Phường 5, Đà Lạt',
    dropoff_location: 'Khu nghỉ dưỡng Swiss-Belresort Tuyền Lâm, Đà Lạt',
    distance_km: 12.0,
    estimated_minutes: 22,
    price: 200000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '8 phút trước',
    customer_name: 'Anh Kiên',
    customer_phone: '0987 666 111'
  },
  {
    id: 'job_dl_02',
    badge: 'Mới',
    pickup_location: 'Chợ đêm Đà Lạt, Nguyễn Thị Minh Khai, Phường 1, Đà Lạt',
    dropoff_location: 'Đồi chè Cầu Đất Farm, Xã Xuân Trường, Đà Lạt',
    distance_km: 23.5,
    estimated_minutes: 38,
    price: 350000,
    service_tags: ['Lái xe hộ', 'Đường dài'],
    status: 'new',
    is_virtual: true,
    time_posted: '22 phút trước',
    customer_name: 'Anh Lâm',
    customer_phone: '0968 444 333'
  },

  // 7. BÌNH DƯƠNG, ĐỒNG NAI & BÀ RỊA - VŨNG TÀU
  {
    id: 'job_bd_01',
    badge: 'Mới',
    pickup_location: 'Nhà hàng Ẩm thực Phố Đôi, Bạch Đằng, TP. Thủ Dầu Một',
    dropoff_location: 'Khu công nghiệp VSIP 1, Đại lộ Bình Dương, Thuận An',
    distance_km: 11.5,
    estimated_minutes: 20,
    price: 160000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '3 phút trước',
    customer_name: 'Anh Trọng',
    customer_phone: '0919 222 555'
  },
  {
    id: 'job_bd_02',
    badge: 'Mới',
    pickup_location: 'Aeon Mall Bình Dương Canary, Đại lộ Bình Dương, Thuận An',
    dropoff_location: 'Chung cư Bcons Green View, Đông Hòa, TP. Dĩ An',
    distance_km: 9.8,
    estimated_minutes: 18,
    price: 140000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '7 phút trước',
    customer_name: 'Chị Oanh',
    customer_phone: '0903 888 111'
  },
  {
    id: 'job_dna_01',
    badge: 'Mới',
    pickup_location: 'Nhà hàng K-Pub, Pegasus Plaza, Võ Thị Sáu, Biên Hòa, Đồng Nai',
    dropoff_location: 'Khu công nghiệp Amata, Xa lộ Hà Nội, Long Bình, Biên Hòa',
    distance_km: 7.5,
    estimated_minutes: 15,
    price: 120000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '10 phút trước',
    customer_name: 'Anh Sang',
    customer_phone: '0972 333 999'
  },
  {
    id: 'job_vt_01',
    badge: 'Cuốc HOT',
    pickup_location: 'Quán Hải Sản Gành Hào 1, 03 Trần Phú, Phường 5, Vũng Tàu',
    dropoff_location: 'Khu du lịch Bãi Sau (Đường Thùy Vân), Phường Thắng Tam, Vũng Tàu',
    distance_km: 6.5,
    estimated_minutes: 13,
    price: 110000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '4 phút trước',
    customer_name: 'Anh Phát',
    customer_phone: '0981 444 777'
  },
  {
    id: 'job_vt_02',
    badge: 'Mới',
    pickup_location: 'Quảng trường Bãi Sau, Thùy Vân, TP. Vũng Tàu',
    dropoff_location: 'The Grand Ho Tram Strip, Xã Phước Thuận, Xuyên Mộc',
    distance_km: 43.0,
    estimated_minutes: 50,
    price: 530000,
    service_tags: ['Lái xe hộ', 'Đường dài'],
    status: 'new',
    is_virtual: true,
    time_posted: '15 phút trước',
    customer_name: 'Anh Kha',
    customer_phone: '0907 111 666'
  },

  // 8. NINH BÌNH, NGHỆ AN & CẦN THƠ
  {
    id: 'job_nb_01',
    badge: 'Mới',
    pickup_location: 'Nhà hàng Dê Chính Thư, Thôn Khê Thượng, Hoa Lư, Ninh Bình',
    dropoff_location: 'Quảng trường Đinh Tiên Hoàng Đế, TP. Ninh Bình',
    distance_km: 7.8,
    estimated_minutes: 14,
    price: 130000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '6 phút trước',
    customer_name: 'Anh Vũ',
    customer_phone: '0915 666 222'
  },
  {
    id: 'job_nb_02',
    badge: 'Mới',
    pickup_location: 'Quần thể Danh thắng Tràng An, Ninh Xuân, Hoa Lư, Ninh Bình',
    dropoff_location: 'Chùa Bái Đính, Xã Gia Sinh, Gia Viễn, Ninh Bình',
    distance_km: 12.0,
    estimated_minutes: 20,
    price: 170000,
    service_tags: ['Xe tiện chuyến', 'Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '13 phút trước',
    customer_name: 'Chị Hà',
    customer_phone: '0983 555 111'
  },
  {
    id: 'job_na_01',
    badge: 'Cuốc HOT',
    pickup_location: 'Nhà hàng Sen Vàng, 114 Lê Hồng Phong, Trường Thi, TP. Vinh',
    dropoff_location: 'Quảng trường Bình Minh, Bãi biển Cửa Lò, Nghệ An',
    distance_km: 16.5,
    estimated_minutes: 24,
    price: 220000,
    service_tags: ['Lái xe hộ', 'Đường dài'],
    status: 'new',
    is_virtual: true,
    time_posted: '5 phút trước',
    customer_name: 'Anh Hùng',
    customer_phone: '0979 222 888'
  },
  {
    id: 'job_na_02',
    badge: 'Mới',
    pickup_location: 'Sân bay Quốc tế Vinh, Xã Nghi Liên, TP. Vinh, Nghệ An',
    dropoff_location: 'Thị trấn Diễn Châu, Huyện Diễn Châu, Nghệ An',
    distance_km: 37.0,
    estimated_minutes: 44,
    price: 460000,
    service_tags: ['Lái xe hộ', 'Đưa đón sân bay'],
    status: 'new',
    is_virtual: true,
    time_posted: '18 phút trước',
    customer_name: 'Anh Tuệ',
    customer_phone: '0918 444 999'
  },
  {
    id: 'job_ct_01',
    badge: 'Mới',
    pickup_location: 'Bến Ninh Kiều, Đường Hai Bà Trưng, Tân An, Ninh Kiều, Cần Thơ',
    dropoff_location: 'Khu dân cư Hưng Phú 1, Cái Răng, Cần Thơ',
    distance_km: 6.5,
    estimated_minutes: 14,
    price: 120000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '8 phút trước',
    customer_name: 'Anh Lợi',
    customer_phone: '0939 123 789'
  },

  // 9. CÁC ĐỊA BÀN PHỔ BIẾN KHÁC (THÁI NGUYÊN, PHÚ THỌ, HUẾ, LÀO CAI, ĐẮK LẮK)
  {
    id: 'job_tn_01',
    badge: 'Mới',
    pickup_location: 'Nhà hàng Lẩu nướng BBQ, Hoàng Văn Thụ, TP. Thái Nguyên',
    dropoff_location: 'Khu công nghiệp Sông Công 1, TP. Sông Công, Thái Nguyên',
    distance_km: 20.5,
    estimated_minutes: 30,
    price: 260000,
    service_tags: ['Lái xe hộ', 'Đường dài'],
    status: 'new',
    is_virtual: true,
    time_posted: '12 phút trước',
    customer_name: 'Anh Khánh',
    customer_phone: '0986 777 333'
  },
  {
    id: 'job_pt_01',
    badge: 'Mới',
    pickup_location: 'Nhà hàng Phương Nam, Đường Tiên Dung, Tiên Cát, TP. Việt Trì',
    dropoff_location: 'Khu Di tích Lịch sử Đền Hùng, Hy Cương, Việt Trì, Phú Thọ',
    distance_km: 12.0,
    estimated_minutes: 18,
    price: 160000,
    service_tags: ['Lái xe hộ'],
    status: 'new',
    is_virtual: true,
    time_posted: '14 phút trước',
    customer_name: 'Anh Tùng',
    customer_phone: '0974 555 888'
  },
  {
    id: 'job_hue_01',
    badge: 'Mới',
    pickup_location: 'Khách sạn Vinpearl Hotel Huế, 50A Hùng Vương, Phú Nhuận, Huế',
    dropoff_location: 'Bãi biển Thuận An, Thị trấn Thuận An, Phú Vang, Thừa Thiên Huế',
    distance_km: 15.0,
    estimated_minutes: 25,
    price: 210000,
    service_tags: ['Lái xe hộ', 'Đường dài'],
    status: 'new',
    is_virtual: true,
    time_posted: '19 phút trước',
    customer_name: 'Chị Cẩm',
    customer_phone: '0905 999 333'
  },
  {
    id: 'job_lc_01',
    badge: 'Cuốc HOT',
    pickup_location: 'Khách sạn Mường Thanh Grand Lào Cai, 086 Thanh Niên, Duyên Hải',
    dropoff_location: 'Quảng trường Trung tâm Sa Pa, Thị xã Sa Pa, Lào Cai',
    distance_km: 33.5,
    estimated_minutes: 50,
    price: 490000,
    service_tags: ['Đường dài', 'Xe tiện chuyến'],
    status: 'new',
    is_virtual: true,
    time_posted: '23 phút trước',
    customer_name: 'Anh Sơn',
    customer_phone: '0912 666 444'
  },
  {
    id: 'job_bmt_01',
    badge: 'Mới',
    pickup_location: 'Bảo tàng Thế giới Cà phê, Nguyễn Đình Chiểu, Buôn Ma Thuột',
    dropoff_location: 'Sân bay Buôn Ma Thuột, Xã Hòa Thắng, TP. Buôn Ma Thuột',
    distance_km: 9.5,
    estimated_minutes: 16,
    price: 150000,
    service_tags: ['Lái xe hộ', 'Đưa đón sân bay'],
    status: 'new',
    is_virtual: true,
    time_posted: '26 phút trước',
    customer_name: 'Anh Y Blo',
    customer_phone: '0983 111 555'
  }
];

async function seed() {
  try {
    console.log(`Starting to seed ${popularTrips.length} popular trips...`);

    let createdCount = 0;
    for (const tripData of popularTrips) {
      // Upsert trip by id
      const existing = await Trip.findByPk(tripData.id);
      if (!existing) {
        await Trip.create({
          ...tripData,
          driver_id: null,
          created_at: new Date(),
          updated_at: new Date()
        });
        createdCount++;
      } else {
        await existing.update(tripData);
      }
    }

    const totalNewTrips = await Trip.count({ where: { status: 'new' } });
    console.log(`Successfully seeded! Inserted/Updated: ${popularTrips.length} trips.`);
    console.log(`Current total 'new' trips in database: ${totalNewTrips}`);
    process.exit(0);
  } catch (error) {
    console.error('Error seeding 50 trips:', error);
    process.exit(1);
  }
}

seed();
